config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  authenticated :user do
    root 'comments#index', as: :newsfeed
    resources :families do
      resources :comments
    end
    resources :users do
      resources :tasks
    end
    get 'profile' => 'users#profile', as: :profile
    post 'create_user' => 'users#create', as: :create_user
    post '/users/:user_id/tasks/:id/finish(.:format)' => 'tasks#finish', as: :finish_task
  end
  
  devise_scope :user do
    root 'devise/sessions#create'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :presence => true
  belongs_to :family
  belongs_to :user
end

app/models/family.rb
class Family < ActiveRecord::Base
  validates :name, :people, :presence => true
  has_many :comments, :dependent => :destroy
  
  def display_name
    "#{name}, #{people}"
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :name, :email, :presence => true
  devise :database_authenticatable, :recoverable, 
         :rememberable, :trackable, :validatable
  has_many :comments, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
  
end

app/controllers/allcomments_controller.rb
class AllcommentsController < ApplicationController
  before_action :find_comment, only: [:destroy, :edit, :update]
  
  def new
  end

  def index
    
    Family.order('id').each do |oneFamily|
      if @allcomments == nil
        @allcomments = oneFamily.comments
      end
      @allcomments.append(oneFamily.comments)
    end
    
    # byebug
    
    @allcomments = @allcomments.order(:created_at)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  before_action :find_family, only: [:create, :edit, :update, :destroy]
  before_action :find_comment, only: [:destroy, :edit, :update]
  
  def create
    @comment = @family.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to family_path(@family)
    # else
    #   render 'new'
    # end
  end
  
  def new
    @comment = Comment.new
  end
  
  def index
    if !current_user.admin?
      @comments = Comment.where("confidential = ? OR user_id = ?", false, current_user.id).order(:created_at).reverse
    else
      @comments = Comment.order(:created_at).reverse
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update(comment_params)
      redirect_to family_path(@family)
    else
      render 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to family_path(@family)
  end
  
  private 
    def comment_params
      params.require(:comment).permit(:content, :confidential)
    end
    
    def find_family
      @family = Family.find(params[:family_id])
    end
      
    def find_comment
      @comment = @family.comments.find(params[:id])
    end
    
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  
  before_action :find_family, only: [:show, :edit, :update, :destroy]
  before_action :get_statuses, only: [:edit, :new]

  def show
  end
  
  def index
    @families = Family.order(:name)
  end
  
  def edit 
  end
  
  def update
    @family.update_attributes!(family_params)
    flash[:notice] = "#{@family.name} family was successfully updated."
    redirect_to family_path(@family)
  end
    
  def new
    @family = Family.new
  end
  
  def create
    @family = Family.create!(family_params)
    flash[:notice] = "#{@family.name} family was successfully created."
    redirect_to families_path
  end
  
  def destroy
    @family.destroy
    flash[:notice] = "Family '#{@family.name}' deleted."
    redirect_to families_path
  end
  
  def show_comments
    if !current_user.admin?
      coms = Comment.where("(confidential = ? AND family_id = ?) OR (confidential = ? AND user_id = ? AND family_id = ?)", false, @family.id, true, current_user.id, @family.id).order(:created_at).reverse
    else
      coms = Comment.where("family_id = ?", @family.id).order(:created_at).reverse
    end
  end
  helper_method :show_comments
  
  private
  
    def family_params
      params.require(:family).permit(:name, :people, :status, :phone, :email)
    end
    
    def find_family
      @family = Family.find(params[:id])
    end
    
    def get_statuses
      @statuses = ['New Member', 'Longtime', 'Non-Member', 'Prospective', 
                   'In Reach', 'Friend of BE', 'Ex-Member', 'Deceased']
    end
  
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :find_user, only: [:create, :edit, :update, :destroy, :finish]
  before_action :find_task, only: [:destroy, :edit, :update, :finish]
  
  def create
    @task = @user.tasks.create(task_params)
    @task.admin_id = current_user.id
    @task.completed = false
    if @task.save
      TaskMailer.notify_task(@user, @task, current_user).deliver
    end
    redirect_to user_path(@user)
    # else
    #   render 'new'
    # end
  end
  
  def edit
  end
  
  def finish
    @task.completed = true
    @task.save!
    redirect_to user_path(@user)
  end
  
  def update
    if @task.update(task_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end
  
  def destroy
    @task.destroy
    redirect_to user_path(@user)
  end
  
  private 
    def task_params
      params.require(:task).permit(:content, :priority, :user_id)
    end
    
    def find_user
      @user = User.find(params[:user_id])
    end
      
    def find_task
      @task = @user.tasks.find(params[:id])
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @user_tasks = Task.where(user_id: @user.id)
    @pending_tasks = @user_tasks.where(completed: false)
    @completed_tasks = @user_tasks.where(completed: true)
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes!(user_params)
    flash[:notice] = "#{@user.name} was successfully updated."
    redirect_to user_path(@user)
  end
  
  def profile
    @user = current_user
    @user_tasks = Task.where(user_id: @user.id)
    @pending_tasks = @user_tasks.where(completed: false)
    @completed_tasks = @user_tasks.where(completed: true)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.create!(user_params)
    flash[:notice] = "#{@user.name} was successfully created."
    redirect_to users_path
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User '#{@user.name}' deleted."
    redirect_to users_path
  end

  private
  
    def user_params
      params.require(:user).permit(:name, :email, :phone, :admin, :password, :password_confirmation)
    end
end

app/helpers/allcomments_helper.rb
module AllcommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/allcomments/index.html.erb
<h1>All comments:</h1>

<% @allcomments.each do |comment| %>
  
  <div class = "center jumbotron">
    <%= " From " %>
    <%= Family.find(comment.family_id).name%>
    <%= " family:" %>
    <%= simple_format "\n"%>
    
    <%= comment.content %>
    <%= simple_format "\n" %>
    <%= distance_of_time_in_words_to_now(comment.created_at, options = {})  %>
    <%= " ago.  " %>
    <%= link_to 'Edit', edit_family_comment_path(comment.family, comment) %>
  </div>
<% end %>

app/views/allcomments/new.html.erb
<h1>Allcomments#new</h1>
<p>Find me in app/views/allcomments/new.html.erb</p>

app/views/comments/_comment.html.erb
<div class = "center jumbotron">
  <div class="comment-container">
    <table class="table table-condensed">
      <tbody>
        <tr>
          <p><%= comment.content %></p>
        </tr>
        <tr>
          <% if comment.user_id == current_user.id or current_user.admin? %>
          
          <%= link_to 'Edit', edit_family_comment_path(comment.family, comment) %>
          <h> &nbsp;&nbsp;&nbsp;&nbsp; </h>
          <%= link_to 'Delete', family_comment_path(comment.family, comment), method: :delete %> 
            <!--data: {confirm: "Are you sure?" } %>-->
          <% end %>
        </tr>
        <tr>
          <td><h5><%= comment.user.name %> on the <%= comment.family.name %> Family</h5></td>
          <td><h5><%= time_ago_in_words(comment.created_at)%> ago</h5></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@family, @family.comments.build]) do |f| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :content, label: "Comment" %>
      <%= f.label :confidential, "Confidential" %>
      <%= f.check_box :confidential, label: "Confidential" %>
    </li>
  </ul>
  <div class = "buttonControl">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for([@family, @comment]) do |f| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :content, label: "Comment" %>
      <%= f.label :confidential, "Confidential" %>
      <%= f.check_box :confidential, label: "Confidential" %>
    </li>
  </ul>
  <div class = "buttonControl">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Newsfeed:</h1>

<div class="commentContainer">
    The last time you signed in was <%= time_ago_in_words(current_user.last_sign_in_at)%> ago
    <% @comments.each do |comment| %>
        <%= render comment %>
    <% end %>
</div>

app/views/families/_form.html.erb
<%= simple_form_for @family do |f|%>

  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :name, label: 'Name' %>
      <%= f.input :people, label: 'Members' %>
      <%= f.input :status, collection: @statuses, prompt: 'Status', selected: 'New Member' %>
      <%= f.input :phone, label: 'Phone' %>
      <%= f.input :email, label: 'Email' %>
    </li>
  </ul>
  
  <div class = "buttonControl">
    <%= f.button :submit, label: 'Add Family' %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Edit Existing Family</h1>

<%= simple_form_for @family do |f|%>

  <%= f.input :name, label: 'Name' %>
  <%= f.input :people, label: 'Members' %>
  <%= f.input :status, collection: @statuses, prompt: 'Status', selected: @family.status %>
    
  <%= f.input :phone, label: 'Phone' %>
  <%= f.input :email, label: 'Email' %>
  <%= f.button :submit, label: 'Update Family Information' %>
<% end %>

app/views/families/index.html.erb
<h1>Welcome to the Families Page</h1>


<table class="table table-striped">
  <tr>
    <th>Family Name</th>
    <th>Status</th>
    <th>Phone Number</th>
    <th>Email</th>
    <% if user_signed_in? %>
      <th>More Info</th>
    <% end %>
  </tr>
  
  
  
  <% @families.each do |family| %>
    <tr>
        
      <td><%= family.display_name %></td>
      <td><%= family.status %></td>
      <td><%= family.phone %></td>
      <td><%= family.email %></td>
      <% if user_signed_in? %> 
        <td><%= link_to "More Info about #{family.name} Family", family_path(family) %></td>
      <% end %>
      
    </tr>
  <% end %>
</table>


<% if user_signed_in? %>
  <%=link_to "Add Family", new_family_path%>
<% end %>

app/views/families/new.html.erb
<h1>Create New Family</h1>

<%= render 'form' %> 

app/views/families/show.html.erb
<h2><%=@family.name%> Family</h2>

<ul class="list-group">
  <li class="list-group-item">
    <p>
    <b>Members:</b>
    <%= @family.people %></p>
  </li>
  <li class="list-group-item">
    <p>
    <b>Status:</b>
    <%= @family.status %></p>
  </li>
  <li class="list-group-item">
    <p>  
    <b>Email:</b>
    <%= @family.email %></p>
  </li>
  <li class="list-group-item">
    <p>
    <b>Phone:</b>
    <%= @family.phone %></p>
  </li>
  <li class="list-group-item">
    <b>Action:</b></br>
    <%= link_to 'Edit Family', edit_family_path(@family) %>
    <% if current_user and current_user.admin? %>
      <%= button_to 'Delete Family', family_path(@family), method: :delete %>
      <!--data: { confirm: 'Are you sure you want to delete this family?' } %>-->
    <% end %>
    <%= link_to 'Back to family list', families_path %>
  </li>
</ul>

</br>

<h3>Add a comment:</h3>
<%= render 'comments/form' %>

</br>

<h3>Comments:</h3>
<div class="commentContainer">
  <%= render show_comments %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Congregation B'nai Emunah</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Families", families_path%></li>
          <li><%= link_to "Profile", profile_path%></li>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
        
      </ul>
      
      
      <ul class="nav navbar-nav navbar-right">
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%=link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
        <% end %>
      </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>Congregation B'nai Emunah</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>


<!--<header class="navbar navbar-fixed-top navbar-inverse">-->
<!--  <div class="container">-->
    <!--<%= link_to "sample app", root_path, id: "logo" %>-->
<!--    <nav>-->
      
<!--    </nav>-->
<!--  </div>-->
<!--</header>-->

  <%= render 'layouts/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <div class = "page-content-main">
    <%= yield %>
  </div>

</body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for([@user, @user.tasks.build]) do |f| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :content, label: "Task" %>
      <%= f.input :priority, label: "Priority", collection: ['Normal', 'Urgent'], selected: 'Normal' %>
    </li>
  </ul>

  <div class = "buttonControl">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <b>Task detail:</b></br>
    <p><%= task.content %></p>
  </li>
  <li class="list-group-item">
    <p><b>Priority:</b>
    <%= task.priority %></p>
    <p><b>Assigned by: </b>
    <%= User.find(task.admin_id).name %> <%= time_ago_in_words(task.created_at)%> ago</p>
  </li>
  <% if task.user_id == current_user.id or current_user.admin? %>
    <li class="list-group-item">
      <b>Action:</b></br>
        <% if not task.completed? %>
          <%= link_to 'Edit', edit_user_task_path(task.user, task) %>
          <%= button_to 'Finish', finish_task_path(@user, task), method: :finish %>
        <% end %>
        <%= link_to 'Delete', user_task_path(task.user, task), method: :delete %> 
          <!--data: {confirm: "Are you sure?" } %>-->
    </li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= simple_form_for([@user, @task]) do |f| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :content, label: "Task" %>
      <%= f.input :priority, collection: ['Normal', 'Urgent'], selected: @task.priority %>
    </li>
  </ul>
  <div class = "buttonControl">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, url: create_user_path do |f|%>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :name, label: 'Name' %>
      <%= f.input :email, label: 'Email' %>
      <%= f.input :phone, label: 'Phone' %>
      <%= f.input :password, label: 'Password' %>
      <%= f.input :password_confirmation, label: 'Confirm password' %>
      <%= f.input :admin, collection: [true, false], selected: false %>
    </li>
  </ul>
  
  <div class = "buttonControl">
    <%= f.button :submit, label: 'Create User' %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Edit Existing User</h1>


<%= simple_form_for @user do |f|%>
  <ul class="list-group">
    <li class="list-group-item">
      <%= f.input :name, label: 'Name' %>
      <%= f.input :email, label: 'Email' %>
      <%= f.input :phone, label: 'Phone' %>
      <% if current_user.admin? %>
        <%= f.input :admin, collection: [true, false], selected: @user.admin %>
      <% end %>
    </li>
  </ul>
  <div class = "buttonControl">
    <%= f.button :submit, label: 'Update User Information' %>
  </div>
<% end %>
  

app/views/users/index.html.erb
<h1>Welcome to the Users Page</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Admin</th>
    <% if current_user.admin? %>
      <th>More Info</th>
    <% end %>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.phone %></td>
    <td><%= user.admin %></td>
    <% if current_user.admin? %> 
      <td><%= link_to "More Info about #{user.name}", user_path(user) %></td>
    <% end %>
  </tr>
  <% end %>
</table>

<% if current_user.admin? %>
  <%= link_to "Add User", new_user_path %>
<% end %>

app/views/users/new.html.erb
<h1>Create New User</h1>

<%= render 'form' %> 

app/views/users/profile.html.erb
<h2>Welcome <%=@user.name%></h2>

<ul class="list-group">
  <li class="list-group-item">
    <p>  
    <b>Email:</b>
    <%= @user.email %></p>
  </li>
  <li class="list-group-item">
    <p>
      <b>Admin Status:</b>
      <%= @user.admin %></p>
  </li>
  <li class="list-group-item">
    <%= link_to 'Edit', edit_user_path(@user) %>
    <%= button_to 'Delete Account', user_path(@user), method: :delete %>
    <!--, data: { confirm: 'Are you sure you want to delete your account?' } %>-->
  </li>
</ul>

<h3>Pending Tasks:</h3>
<%= render @pending_tasks.reverse %>

</br>


<h6>Completed Tasks:</h6>
<%= render @completed_tasks.reverse %>

app/views/users/show.html.erb
<h2>User <%=@user.name%></h2>

  <ul class="list-group">
    <li class="list-group-item">
      <p>  
      <b>Name:</b>
      <%= @user.name %></p>
    </li>
    <li class="list-group-item">
      <p>  
      <b>Email:</b>
      <%= @user.email %></p>
    </li>
    <li class="list-group-item">
      <p>  
      <b>Phone:</b>
      <%= @user.phone %></p>
    </li>
    <li class="list-group-item">
      <p>
      <b>Admin Status:</b>
      <%= @user.admin %></p>
    </li>
    <li class="list-group-item">
      <b>Actions:</b></br>
      <%= link_to 'Edit User', edit_user_path(@user) %>
      <% if current_user.admin? %>
        <%= button_to 'Delete User', user_path(@user), method: :delete %>
          <!--,data: { confirm: 'Are you sure you want to delete this user?' } %>-->
      <% end %>
      <%= link_to 'Back to user list', users_path %>
    </li>
  </ul>

</br>

<% if current_user.admin? %> 
  <h4>Add a Task:</h4>
    <%= render 'tasks/form' %>
  </br>
<% end %>

<h4>Pending Tasks:</h4>
  <%= render @pending_tasks.reverse %>
</br>

<h4>Completed Tasks:</h4>
<%= render @completed_tasks.reverse %>